### ISSUE TITLE
Better help text required

### ISSUE THREAD

**Issue by christopher-henderson** [christopher-henderson/SER_216_Group_Project#13]
Users we left confused after consulting the help menu. As is, it only states that this game is similar to free cell and solitaire, but does not outline the rules or the goals.

**Comment by Ehic** [comment]
Rules section has been added to the help dialog box

**Comment by christopher-henderson** [comment]
Please reference commit that addresses this issue.

**Comment by Ehic** [comment]
f985fd4b4cd207cb524a6f19a1fa520292b21777
