### ISSUE TITLE
Only the far right card can be selected while in three card draw mode.

### ISSUE THREAD

**Issue by christopher-henderson** [christopher-henderson/SER_216_Group_Project#8]
4/9/2015 2:10

Action: Switch to three card draw mode. Start a new game. Draw three cards. Attempt to select one of the three cards that are not the card on the far right. Observe.
Problem: Only the far right card is selectable.
Desired Behavior: All three cards of a three card draw should be selectable.

**Comment by tgharker** [comment]
Actually I’m pretty sure that only the far right card should be selectable. That’s how other solitaire games work “it makes it more difficult”

Tyler

**Comment by christopher-henderson** [comment]
Reviewed the rules and general play. I agree. NAB.

**Comment by tgharker** [comment]
I'm not sure if it is a bug, or me simply doing something wrong, but when I'm running the game and it goes to save the games progress it crashes on ubuntu.

Tyler
________________________________

**Comment by christopher-henderson** [comment]
Why was this posted under issue #8? Doesn't seem related.

Any-ho, this crash doesn't occur on Fedora. Write the bug as an Ubuntu specific issue.
